### ISSUE TITLE
How to build plantuml

### ISSUE THREAD

**Issue by zhaoweiguo** [ammaraskar/sphinx-action#18]
Since plantuml use java, What should i do to use plantuml file.
I tried this:
```
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "source/"
        pre-build-command: "apt-get update -y && apt-get install -y openjdk-8-jdk"
        build-command: "java -version && sphinx-build -b html . _build"
```
I failed show this:
```
FileNotFoundError: [Errno 2] No such file or directory: 'java'
```
Is Any one has any suggestion?
