### ISSUE TITLE
Need explanation

### ISSUE THREAD

**Issue by kridsadakorn** [ammaraskar/sphinx-action#29]
Dear Authors,

I am quite naive about Github Action. What I want to do is to create the HTML documents from a public repository.
Let say, I want to create the HTML documents from NumPy. How could I do that?
Here is my naive script, it doesn't work. It would be great if you help me to point it out.
```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: numpy/numpy
        path: .
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . _build"
        docs-folder: "doc/"
 ```
 
 Thank you.
