### ISSUE TITLE
Build command make latexpdf (latexmk: Command not found)

### ISSUE THREAD

**Issue by scottclowe** [ammaraskar/sphinx-action#32]
The latex build action
```
    - name: Build PDF docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"
```
was previously running correctly, but has (today) started failing with the error:
```
make[1]: latexmk: Command not found
```

Here's links to the relevant files:
- [Workflow file](https://github.com/scottclowe/python-template-repo/blob/e89ae8b/.github/workflows/docs.yaml#L87-L92)
- [Broken run](https://github.com/scottclowe/python-template-repo/pull/92/checks?check_run_id=3349528187#step:7:138)
- [Last successful run](https://github.com/scottclowe/python-template-repo/runs/3302388563?check_suite_focus=true#step:7:1652)

For the repo in question, no documentation changes or changes to the documentation workflow have occurred between the last successful run 6 days ago and the recent failing build. I note that [no commits](https://github.com/ammaraskar/sphinx-action/commits/master) have been made to ammaraskar/sphinx-action in the past 6 days. And the [sphinxdoc base docker image](https://hub.docker.com/layers/sphinxdoc/sphinx/2.4.4/images/sha256-64a91f76bd196e7d4d860f17ebfd0140c22e00c8d7cd1316812184b974d0499f?context=explore) has not been changed.

I'm at a loss to understand what is causing this problem.
