### ISSUE TITLE
Cannot run apt update 

### ISSUE THREAD

**Issue by maxnoe** [ammaraskar/sphinx-action#33]
Trying to install additional packages, running `apt update --yes` fails with an error (presumably something to do with the new debian release?)
Config:
```
  with:
    docs-folder: docs/
    pre-build-command: apt update --yes && apt install --yes git build-essential pandoc
```

Log:
```
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Reading package lists...
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
```

Link to a build:
https://github.com/cta-observatory/ctapipe/pull/1774/checks?check_run_id=3424315763

**Comment by ocket8888** [comment]
I'm wondering if skipping the update would help - otherwise they may have to update the base image to bullseye

**Comment by ocket8888** [comment]
Update: Yeah, if you skip the update it seems to be working okay. Build link: https://github.com/apache/trafficcontrol/pull/6158/checks?check_run_id=3495291877

So instead of
```yaml
  with:
    docs-folder: docs/
    pre-build-command: apt update --yes && apt install --yes git build-essential pandoc
```
just
```yaml
  with:
    docs-folder: docs/
    pre-build-command: apt install --yes git build-essential pandoc
```
should work.
