### ISSUE TITLE
Make the action compatible with sphinx-multiversion

### ISSUE THREAD

**Issue by snorkman88** [ammaraskar/sphinx-action#51]
I have tried replacing the custom build command with: 
```
      - name: Build docs using action
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/source/"
          build-command: "pip install sphinx-multiversion && sphinx-multiversion . docs/_build"
```
but it seems it is not possible to use this action with sphinx-multiversion yet, would it be possible to support such feature?
