### ISSUE TITLE
Move master off of 2.4.4

### ISSUE THREAD

**Issue by nicholasphair** [ammaraskar/sphinx-action#57]
#56 added support for different Sphinx versions through tags. `master`, however, still points to `2.4.4`.  That was purposeful. It was done to not immediately breaks builds and give people time to kick the tires on the tagging approach. 

This issue is for tracking/coming up with a sane policy for moving the the `master` pointer to something more recent. Perhaps just a message in the logs encouraging folks to pin a specific version.

**Comment by yinchi** [comment]
Perhaps use env to set the Docker image version?  Default to `latest` if not set.

```yaml
- name: Sphinx Build
  uses: ammaraskar/sphinx-action@master
    with:
      docs-folder: "docs"
    env:
      tag: "7.4.7"
```

This way, the versioning of the Github Action is divorced from the version of Sphinx itself.

**Comment by nicholasphair** [comment]
Does that build an image each time the action is run? Would that not be slow? If not that could be a nice change.

Just to be clear, in case it is not, you can specify the sphinx version already:
```
- name: Sphinx Build
  uses: ammaraskar/sphinx-action@7.0.1
    with:
      docs-folder: "docs"
```

Good for end-users, but for maintainers of this project it requires effort to keep dockerfiles and tags in sync with the upstream sphinx project. Something that nobody really has time for and is why the versioning lags behind. That might be good motivation to consider #55. Though, that is certainly not my call.

In any case, the `dev` branch does have a script and a nightly workflow to try and automate this synchronization process. Maybe that can be merged @ammaraskar.
